apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: awssecretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets