{{- if .Values.env.enabled }}
{{- range .Values.env.envFrom }}
{{- if hasKey . "secretRef" }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}-{{ .secretRef.name }}-sbx
spec:
  externalSecretName: {{ .secretRef.name }}
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ $.Values.namespace }}
  externalSecretSpec:
    secretStoreRef:
      name: awssecretsmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: {{ .secretRef.name }}
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: {{ .secretRef.name }}
{{- end }}
{{- end }}
{{- end }}